# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025-present Masaya Taniguchi

[test]
preload = ["./tests/happydom.ts"]
coverage = true
coverageThreshold = 1.0

[serve.static]
plugins = ["./scripts/bun-plugin-sass.ts"]
